# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['english_app.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('Donate-Icon-PNG-Clipart-Background.png', '.'),
        ('logo hd.png', '.'),
        ('application.png', '.'),
        ('words.csv', '.'),
        ('words.txt', '.'),
        ('icon/play-button.png', 'icon'),
        ('icon/stop-button.png', 'icon'),
        ('icon/Notify.png', 'icon'),
        ('icon/OpenEditor.png', 'icon'),
        ('icon/document-editor.png', 'icon'),
        ('icon/document-editor_36.png', 'icon'),
        ('icon/clean all.png', 'icon'),
        ('icon/clean all red.png', 'icon'),
        ('icon/Remove selected.png', 'icon'),
        ('icon/search words.png', 'icon'),
        ('icon/add.png', 'icon'),
    ],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='english_app',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='app.ico',
)
